POST http://localhost:5000/user/register
Content-Type: application/json

{
    "name":"tej",
    "email":"tej@gmail.com",
    "password":"tej123"
}
###
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email":"teja@gmail.com",
    "password":"teja123"
}

###
DELETE http://localhost:5000/user/delete/6805d20c17da3ea529ca22d8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlamFAZ21haWwuY29tIiwiaWQiOiI2ODA1YzdmODFlOGE3MzgyNWM0NGMzNGIiLCJpYXQiOjE3NDYyNjMzNTksImV4cCI6MTc0NjI2Njk1OX0.-n-dCcVSRXxnVJ1JwIMkby8hhK7bmYDubAXU3Qk2x8U
###
GET http://localhost:5000/user/users